### ISSUE TITLE
incomplete support of numpy types

### ISSUE THREAD

**Issue by shaimach** [hmallen/numpyencoder#1]
Hi,

Current code does not support bool_, void and complex types.
This causes issues when encoding certain dtype-s (e.g. from h5py files).

Adding the following lines will resolve the issue:

        elif isinstance(obj,(np.complex_,np.complex64,np.complex128)):
            return {'real': obj.real, 'imag': obj.imag}
        
        elif isinstance(obj, (np.bool_)):
            return bool(obj)

        elif isinstance(obj, (np.void)): 
            return None

**Comment by hmallen** [comment]
Thanks for your suggestion. Sorry it has taken so long to get around to this. I'm going to work on implementing this now.

**Comment by hmallen** [comment]
Changes implemented and project moved to v0.2.0.

**Comment by shaimach** [comment]
Thank you !
