### ISSUE TITLE
No module named "numpyencoder"

### ISSUE THREAD

**Issue by artun3e** [hmallen/numpyencoder#3]
I am using python 3.8.1 and already downloaded numpyencoder using  **pip install numpyencoder**.  However, I can't import it. Could you please help me ?

**Comment by Erik-BM** [comment]
Do you have python 2 installed? If so, you should use `pip3 install numpyencoder` to install for python 3. Works for me on 3.8.2.

**Comment by artun3e** [comment]
> Do you have python 2 installed? If so, you should use `pip3 install numpyencoder` to install for python 3. Works for me on 3.8.2.

Yes I'm using both python3 and python2. I actually downloaded via **pip3 install numpyencoder** and can see it through /usr/local/lib/python3.8/site-packages however I can't import it. I tried to install & import it on a virtuelenv and my problem is solved. So issue is more likely related to some path issues. Thanks anyways!
